#!/usr/bin/env node

import 'dotenv/config';

import { spawn } from 'node:child_process';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import process from 'node:process';
import readline from 'node:readline';

import { loadOrInitialize, runOnePass } from './orchestrator.js';
import type { RunLogger } from './logger.js';
import { assertSupportedAgentConfig } from './providers/registry.js';
import { getDefaultAgentConfig } from './state.js';
import { showSummaries } from './summaries.js';
import { ClaudeRoundError, CodexRoundError } from './agents.js';
import type { AgentProvider } from './types.js';

function usage(): never {
  console.error('Usage: neal --execute <plan-doc|inline-prompt>');
  console.error('   or: neal --plan <plan-doc>');
  console.error('   or: neal --resume [state-file]');
  console.error('   or: neal --summaries [runs-dir]');
  console.error('Optional new-run flags: --coder-provider <provider> --coder-model <model> --reviewer-provider <provider> --reviewer-model <model>');
  process.exit(1);
}

function isAgentProvider(value: string): value is AgentProvider {
  return value === 'openai-codex' || value === 'anthropic-claude';
}

async function executeRun(state: Awaited<ReturnType<typeof loadOrInitialize>>['state'], statePath: string, logger: RunLogger) {
  runLogger = logger;
  const stopController = createStopController();
  let lastThreadId: string | null = state.codexThreadId;
  let shouldResumeLastThread = false;

  if (process.stdin.isTTY) {
    process.stderr.write('[neal] press q to stop after the current scope\n');
  }

  let finalState;
  try {
    finalState = await runOnePass(state, statePath, logger, {
      shouldStopAfterCurrentScope() {
        return stopController.isStopRequested();
      },
      onCodexThread(threadId) {
        if (threadId) {
          lastThreadId = threadId;
        }
      },
    });
    shouldResumeLastThread =
      stopController.isStopRequested() &&
      finalState.phase === 'codex_scope' &&
      finalState.status === 'running' &&
      Boolean(lastThreadId);
  } finally {
    stopController.cleanup();
  }

  process.stdout.write(
    JSON.stringify(
      {
        ok: true,
        phase: finalState.phase,
        status: finalState.status,
        topLevelMode: finalState.topLevelMode,
        agentConfig: finalState.agentConfig,
        planDoc: finalState.planDoc,
        statePath,
        runDir: finalState.runDir,
        progressJsonPath: finalState.progressJsonPath,
        progressMarkdownPath: finalState.progressMarkdownPath,
        reviewMarkdownPath: finalState.reviewMarkdownPath,
        archivedReviewPath: finalState.archivedReviewPath,
        baseCommit: finalState.baseCommit,
        finalCommit: finalState.finalCommit,
        codexThreadId: finalState.codexThreadId,
        claudeSessionId: finalState.claudeSessionId,
        rounds: finalState.rounds.length,
        findings: finalState.findings.length,
      },
      null,
      2,
    ) + '\n',
  );

  if (shouldResumeLastThread && lastThreadId) {
    process.stderr.write(`[neal] resuming ${lastThreadId}\n`);
    await resumeLastThread(lastThreadId);
  }
}

async function createInlineExecutePlanDoc(cwd: string, prompt: string) {
  const adhocDir = join(cwd, '.neal', 'adhoc');
  await mkdir(adhocDir, { recursive: true });
  const filePath = join(adhocDir, `inline-execute-${Date.now()}.md`);
  const content = [
    '# Inline Execute Prompt',
    '',
    'This prompt was generated by neal from an inline `--execute` argument.',
    '',
    '## Request',
    prompt.trim(),
    '',
    '## Execution Guidance',
    '- Treat this as an ad hoc neal execution request.',
    '- Prefer to finish the request in one scope unless the work clearly requires a follow-up scope.',
    '- If the task completes fully in this scope, return AUTONOMY_DONE.',
    '- If meaningful work remains for a subsequent scope, return AUTONOMY_SCOPE_DONE.',
    '- If the task cannot proceed, return AUTONOMY_BLOCKED with a concrete blocker.',
    '',
  ].join('\n');
  await writeFile(filePath, content, 'utf8');
  return filePath;
}

async function resumeLastThread(threadId: string) {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const child = spawn('codex', ['resume', threadId], {
      stdio: 'inherit',
    });

    child.on('error', rejectPromise);
    child.on('exit', (code, signal) => {
      if (signal) {
        rejectPromise(new Error(`codex resume terminated by signal ${signal}`));
        return;
      }

      if (code === 0) {
        resolvePromise();
      } else {
        rejectPromise(new Error(`codex resume exited with status ${code}`));
      }
    });
  });
}

function createStopController() {
  let stopRequested = false;

  if (!process.stdin.isTTY) {
    return {
      cleanup() {},
      isStopRequested() {
        return stopRequested;
      },
    };
  }

  readline.emitKeypressEvents(process.stdin);
  process.stdin.setRawMode(true);
  process.stdin.resume();

  const onKeypress = (_input: string, key: readline.Key) => {
    if (key.ctrl && key.name === 'c') {
      cleanup();
      process.exit(130);
    }

    if (key.name === 'q') {
      stopRequested = !stopRequested;
      process.stderr.write(
        stopRequested
          ? '\n[neal] stop requested after the current scope\n'
          : '\n[neal] stop request cleared; continuing after the current scope\n',
      );
    }
  };

  process.stdin.on('keypress', onKeypress);

  function cleanup() {
    process.stdin.off('keypress', onKeypress);
    if (process.stdin.isTTY) {
      process.stdin.setRawMode(false);
    }
    process.stdin.pause();
  }

  return {
    cleanup,
    isStopRequested() {
      return stopRequested;
    },
  };
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    usage();
  }

  if (args[0] === '--summaries') {
    await showSummaries(args[1]);
    return;
  }

  let topLevelMode: 'plan' | 'execute' = 'execute';
  let planDoc: string | null = null;
  let resumeStatePath: string | undefined;
  const agentConfig = getDefaultAgentConfig();
  let index = 0;
  let sawExplicitMode = false;

  if (args[index] === '--plan') {
    topLevelMode = 'plan';
    sawExplicitMode = true;
    index += 1;
  } else if (args[index] === '--execute') {
    sawExplicitMode = true;
    index += 1;
  }

  const firstArg = args[index];
  if (!firstArg) {
    usage();
  }

  if (firstArg === '--resume') {
    if (args.length > index + 2) {
      throw new Error('neal --resume accepts only an optional state-file path and does not accept agent config flags');
    }
    resumeStatePath = resolve(args[index + 1] ?? '.neal/session.json');
    await access(resumeStatePath);
    const loaded = await loadOrInitialize(null, process.cwd(), agentConfig, resumeStatePath, topLevelMode);
    assertSupportedAgentConfig(loaded.state.agentConfig);
    await executeRun(loaded.state, loaded.statePath, loaded.logger);
    return;
  }

  index += 1;
  while (index < args.length) {
    const flag = args[index];
    const value = args[index + 1];
    switch (flag) {
      case '--coder-provider':
        if (!value || !isAgentProvider(value)) {
          throw new Error(`Invalid --coder-provider value: ${String(value)}`);
        }
        agentConfig.coder.provider = value;
        index += 2;
        break;
      case '--coder-model':
        if (!value) {
          throw new Error('--coder-model requires a value');
        }
        agentConfig.coder.model = value;
        index += 2;
        break;
      case '--reviewer-provider':
        if (!value || !isAgentProvider(value)) {
          throw new Error(`Invalid --reviewer-provider value: ${String(value)}`);
        }
        agentConfig.reviewer.provider = value;
        index += 2;
        break;
      case '--reviewer-model':
        if (!value) {
          throw new Error('--reviewer-model requires a value');
        }
        agentConfig.reviewer.model = value;
        index += 2;
        break;
      default:
        throw new Error(`Unknown argument: ${flag}`);
    }
  }

  assertSupportedAgentConfig(agentConfig);

  if (!sawExplicitMode) {
    usage();
  }
  try {
    planDoc = resolve(firstArg);
    await access(planDoc);
  } catch {
    if (topLevelMode !== 'execute') {
      throw new Error(`Plan file not found: ${firstArg}`);
    }
    planDoc = await createInlineExecutePlanDoc(process.cwd(), firstArg);
  }

  const loaded = await loadOrInitialize(planDoc, process.cwd(), agentConfig, undefined, topLevelMode);
  assertSupportedAgentConfig(loaded.state.agentConfig);
  await executeRun(loaded.state, loaded.statePath, loaded.logger);
}

let runLogger: RunLogger | undefined;

void main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  void runLogger?.event('run.failed', {
    message,
    codexThreadId: error instanceof CodexRoundError ? error.threadId : null,
    claudeSessionId: error instanceof ClaudeRoundError ? error.sessionId : null,
    claudeSubtype: error instanceof ClaudeRoundError ? error.subtype : null,
  });
  if (error instanceof Error && error.stack) {
    void runLogger?.stderr(`[fatal] ${error.stack}\n`);
  } else {
    void runLogger?.stderr(`[fatal] ${message}\n`);
  }
  if (error instanceof CodexRoundError && error.threadId) {
    process.stderr.write(`[neal] ${message} (codex thread: ${error.threadId})\n`);
  } else if (error instanceof ClaudeRoundError && error.sessionId) {
    process.stderr.write(`[neal] ${message} (claude session: ${error.sessionId})\n`);
  } else {
    process.stderr.write(`[neal] ${message}\n`);
  }
  process.exit(1);
});
