#!/usr/bin/env node

import 'dotenv/config';

import { spawn } from 'node:child_process';
import { access, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import process from 'node:process';
import readline from 'node:readline';

import {
  InteractiveBlockedRecoveryPendingTurnError,
  InteractiveBlockedRecoveryTurnLimitError,
  loadOrInitialize,
  recordInteractiveBlockedRecoveryGuidance,
  runOnePass,
} from './orchestrator.js';
import type { RunLogger } from './logger.js';
import { assertSupportedAgentConfig } from './providers/registry.js';
import { getDefaultAgentConfig, loadState } from './state.js';
import { showSummaries } from './summaries.js';
import { CoderRoundError, ReviewerRoundError } from './agents.js';
import type { AgentProvider } from './types.js';

type SessionLaunchCommand = {
  command: string;
  args: string[];
};

type SessionLaunchTarget = {
  role: 'coder' | 'reviewer';
  provider: AgentProvider;
  sessionHandle: string;
};

function usage(): never {
  console.error('Usage: neal --execute <plan-doc|inline-prompt>');
  console.error('   or: neal --plan <plan-doc>');
  console.error('   or: neal --resume [state-file]');
  console.error('   or: neal --recover [state-file] --message <guidance>  # then run neal --resume');
  console.error('   or: neal --resume-coder [state-file]');
  console.error('   or: neal --resume-reviewer [state-file]');
  console.error('   or: neal --summaries [runs-dir]');
  console.error('Optional new-run flags: --coder-provider <provider> --coder-model <model> --reviewer-provider <provider> --reviewer-model <model> --ignore-local-changes');
  process.exit(1);
}

function isAgentProvider(value: string): value is AgentProvider {
  return value === 'openai-codex' || value === 'anthropic-claude';
}

async function executeRun(state: Awaited<ReturnType<typeof loadOrInitialize>>['state'], statePath: string, logger: RunLogger) {
  runLogger = logger;
  const stopController = createStopController();
  let lastCoderSessionHandle: string | null = state.coderSessionHandle;
  let shouldResumeLastThread = false;

  if (process.stdin.isTTY) {
    process.stderr.write('[neal] press q to stop after the current scope\n');
  }

  let finalState;
  try {
    finalState = await runOnePass(state, statePath, logger, {
      shouldStopAfterCurrentScope() {
        return stopController.isStopRequested();
      },
      onCoderSessionHandle(sessionHandle) {
        if (sessionHandle) {
          lastCoderSessionHandle = sessionHandle;
        }
      },
    });
    shouldResumeLastThread =
      stopController.isStopRequested() &&
      finalState.phase === 'coder_scope' &&
      finalState.status === 'running' &&
      Boolean(lastCoderSessionHandle);
  } finally {
    stopController.cleanup();
  }

  const interactiveBlockedRecovery = finalState.interactiveBlockedRecovery;
  const waitingForOperatorGuidance =
    finalState.phase === 'interactive_blocked_recovery' && interactiveBlockedRecovery
      ? interactiveBlockedRecovery.turns.length === interactiveBlockedRecovery.lastHandledTurn
      : false;

  if (waitingForOperatorGuidance) {
    process.stderr.write(`[neal] waiting for operator guidance; use: neal --recover ${statePath} --message \"...\"\n`);
  }

  process.stdout.write(
    JSON.stringify(
      {
        ok: true,
        waitingForOperatorGuidance,
        phase: finalState.phase,
        status: finalState.status,
        topLevelMode: finalState.topLevelMode,
        agentConfig: finalState.agentConfig,
        planDoc: finalState.planDoc,
        statePath,
        runDir: finalState.runDir,
        progressJsonPath: finalState.progressJsonPath,
        progressMarkdownPath: finalState.progressMarkdownPath,
        reviewMarkdownPath: finalState.reviewMarkdownPath,
        archivedReviewPath: finalState.archivedReviewPath,
        baseCommit: finalState.baseCommit,
        finalCommit: finalState.finalCommit,
        coderSessionHandle: finalState.coderSessionHandle,
        reviewerSessionHandle: finalState.reviewerSessionHandle,
        rounds: finalState.rounds.length,
        findings: finalState.findings.length,
      },
      null,
      2,
    ) + '\n',
  );

  if (shouldResumeLastThread && lastCoderSessionHandle) {
    process.stderr.write(`[neal] resuming ${lastCoderSessionHandle}\n`);
    await resumeLastCoderSession(finalState.agentConfig.coder.provider, lastCoderSessionHandle);
  }
}

async function createInlineExecutePlanDoc(cwd: string, prompt: string) {
  const adhocDir = join(cwd, '.neal', 'adhoc');
  await mkdir(adhocDir, { recursive: true });
  const filePath = join(adhocDir, `inline-execute-${Date.now()}.md`);
  const content = [
    '# Inline Execute Prompt',
    '',
    'This prompt was generated by neal from an inline `--execute` argument.',
    '',
    '## Request',
    prompt.trim(),
    '',
    '## Execution Guidance',
    '- Treat this as an ad hoc neal execution request.',
    '- Prefer to finish the request in one scope unless the work clearly requires a follow-up scope.',
    '- If the task completes fully in this scope, return AUTONOMY_DONE.',
    '- If meaningful work remains for a subsequent scope, return AUTONOMY_SCOPE_DONE.',
    '- If the task cannot proceed, return AUTONOMY_BLOCKED with a concrete blocker.',
    '',
  ].join('\n');
  await writeFile(filePath, content, 'utf8');
  return filePath;
}

async function resumeLastCoderSession(provider: AgentProvider, sessionHandle: string) {
  await openSession({
    role: 'coder',
    provider,
    sessionHandle,
  });
}

async function spawnLaunchCommand({ command, args }: SessionLaunchCommand) {
  await new Promise<void>((resolvePromise, rejectPromise) => {
    const child = spawn(command, args, {
      stdio: 'inherit',
    });

    child.on('error', rejectPromise);
    child.on('exit', (code, signal) => {
      if (signal) {
        rejectPromise(new Error(`${command} ${args.join(' ')} terminated by signal ${signal}`));
        return;
      }

      if (code === 0) {
        resolvePromise();
      } else {
        rejectPromise(new Error(`${command} ${args.join(' ')} exited with status ${code}`));
      }
    });
  });
}

function getSessionLaunchCommand(provider: AgentProvider, sessionHandle: string): SessionLaunchCommand {
  switch (provider) {
    case 'openai-codex':
      return {
        command: 'codex',
        args: ['resume', sessionHandle],
      };
    case 'anthropic-claude':
      return {
        command: 'claude',
        args: ['--resume', sessionHandle],
      };
  }
}

async function openSession(target: SessionLaunchTarget) {
  const launch = getSessionLaunchCommand(target.provider, target.sessionHandle);
  process.stderr.write(`[neal] opening ${target.role} session via ${launch.command} ${launch.args.join(' ')}\n`);
  await spawnLaunchCommand(launch);
}

async function openPersistedSession(role: 'coder' | 'reviewer', statePath: string) {
  const state = await loadState(statePath);
  const roleConfig = role === 'coder' ? state.agentConfig.coder : state.agentConfig.reviewer;
  const sessionHandle = role === 'coder' ? state.coderSessionHandle : state.reviewerSessionHandle;

  if (!sessionHandle) {
    throw new Error(`No persisted ${role} session handle found in ${statePath}`);
  }

  await openSession({
    role,
    provider: roleConfig.provider,
    sessionHandle,
  });
}

function createStopController() {
  let stopRequested = false;

  if (!process.stdin.isTTY) {
    return {
      cleanup() {},
      isStopRequested() {
        return stopRequested;
      },
    };
  }

  readline.emitKeypressEvents(process.stdin);
  process.stdin.setRawMode(true);
  process.stdin.resume();

  const onKeypress = (_input: string, key: readline.Key) => {
    if (key.ctrl && key.name === 'c') {
      cleanup();
      process.exit(130);
    }

    if (key.name === 'q') {
      stopRequested = !stopRequested;
      process.stderr.write(
        stopRequested
          ? '\n[neal] stop requested after the current scope\n'
          : '\n[neal] stop request cleared; continuing after the current scope\n',
      );
    }
  };

  process.stdin.on('keypress', onKeypress);

  function cleanup() {
    process.stdin.off('keypress', onKeypress);
    if (process.stdin.isTTY) {
      process.stdin.setRawMode(false);
    }
    process.stdin.pause();
  }

  return {
    cleanup,
    isStopRequested() {
      return stopRequested;
    },
  };
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    usage();
  }

  if (args[0] === '--summaries') {
    await showSummaries(args[1]);
    return;
  }

  if (args[0] === '--recover') {
    let statePath = resolve('.neal/session.json');
    let message: string | null = null;
    let index = 1;

    if (args[index] && !args[index].startsWith('--')) {
      statePath = resolve(args[index]);
      index += 1;
    }

    while (index < args.length) {
      const flag = args[index];
      const value = args[index + 1];
      switch (flag) {
        case '--message':
          if (!value) {
            throw new Error('--recover requires a value for --message');
          }
          message = value;
          index += 2;
          break;
        default:
          throw new Error(`Unknown argument: ${flag}`);
      }
    }

    if (!message) {
      throw new Error('neal --recover requires --message <guidance>');
    }

    await access(statePath);
    const loaded = await loadOrInitialize(null, process.cwd(), getDefaultAgentConfig(), statePath, 'execute');
    assertSupportedAgentConfig(loaded.state.agentConfig);
    if (loaded.state.topLevelMode !== 'execute') {
      throw new Error('--recover is only supported for execute-mode runs');
    }
    let nextState;
    try {
      nextState = await recordInteractiveBlockedRecoveryGuidance(loaded.statePath, message, loaded.logger);
    } catch (error) {
      if (error instanceof InteractiveBlockedRecoveryPendingTurnError) {
        process.stdout.write(
          JSON.stringify(
            {
              ok: false,
              code: 'interactive_blocked_recovery_pending_turn',
              message: error.message,
              statePath: loaded.statePath,
              runDir: loaded.state.runDir,
              pendingTurn: error.pendingTurn,
              recoveryTurns: loaded.state.interactiveBlockedRecovery?.turns.length ?? 0,
              nextStep: 'Run `neal --resume` to let the coder handle the pending recovery turn before recording more guidance.',
            },
            null,
            2,
          ) + '\n',
        );
        return;
      }
      if (error instanceof InteractiveBlockedRecoveryTurnLimitError) {
        process.stdout.write(
          JSON.stringify(
            {
              ok: false,
              code: 'interactive_blocked_recovery_turn_limit',
              message: error.message,
              statePath: loaded.statePath,
              runDir: loaded.state.runDir,
              maxTurns: error.maxTurns,
              recoveryTurns: loaded.state.interactiveBlockedRecovery?.turns.length ?? 0,
              nextStep: 'Run `neal --resume` and choose `terminal_block` or `replace_current_scope`.',
            },
            null,
            2,
          ) + '\n',
        );
        return;
      }
      throw error;
    }
    process.stderr.write(`[neal] recovery guidance recorded; run: neal --resume ${loaded.statePath}\n`);
    process.stdout.write(
      JSON.stringify(
        {
          ok: true,
          phase: nextState.phase,
          status: nextState.status,
          statePath: loaded.statePath,
          runDir: nextState.runDir,
          recoveryTurns: nextState.interactiveBlockedRecovery?.turns.length ?? 0,
          nextStep: `Run \`neal --resume ${loaded.statePath}\` to process the recovery guidance.`,
        },
        null,
        2,
      ) + '\n',
    );
    return;
  }

  let topLevelMode: 'plan' | 'execute' = 'execute';
  let planDoc: string | null = null;
  let resumeStatePath: string | undefined;
  const agentConfig = getDefaultAgentConfig();
  let ignoreLocalChanges = false;
  let index = 0;
  let sawExplicitMode = false;

  if (args[index] === '--plan') {
    topLevelMode = 'plan';
    sawExplicitMode = true;
    index += 1;
  } else if (args[index] === '--execute') {
    sawExplicitMode = true;
    index += 1;
  }

  const firstArg = args[index];
  if (!firstArg) {
    usage();
  }

  if (firstArg === '--resume-coder' || firstArg === '--resume-reviewer') {
    if (args.length > index + 2) {
      throw new Error(`${firstArg} accepts only an optional state-file path`);
    }
    const statePath = resolve(args[index + 1] ?? '.neal/session.json');
    await access(statePath);
    await openPersistedSession(firstArg === '--resume-coder' ? 'coder' : 'reviewer', statePath);
    return;
  }

  if (firstArg === '--resume') {
    if (args.length > index + 2) {
      throw new Error('neal --resume accepts only an optional state-file path and does not accept agent config flags');
    }
    resumeStatePath = resolve(args[index + 1] ?? '.neal/session.json');
    await access(resumeStatePath);
    const loaded = await loadOrInitialize(null, process.cwd(), agentConfig, resumeStatePath, topLevelMode);
    assertSupportedAgentConfig(loaded.state.agentConfig);
    await executeRun(loaded.state, loaded.statePath, loaded.logger);
    return;
  }

  index += 1;
  while (index < args.length) {
    const flag = args[index];
    const value = args[index + 1];
    switch (flag) {
      case '--coder-provider':
        if (!value || !isAgentProvider(value)) {
          throw new Error(`Invalid --coder-provider value: ${String(value)}`);
        }
        agentConfig.coder.provider = value;
        index += 2;
        break;
      case '--coder-model':
        if (!value) {
          throw new Error('--coder-model requires a value');
        }
        agentConfig.coder.model = value;
        index += 2;
        break;
      case '--reviewer-provider':
        if (!value || !isAgentProvider(value)) {
          throw new Error(`Invalid --reviewer-provider value: ${String(value)}`);
        }
        agentConfig.reviewer.provider = value;
        index += 2;
        break;
      case '--reviewer-model':
        if (!value) {
          throw new Error('--reviewer-model requires a value');
        }
        agentConfig.reviewer.model = value;
        index += 2;
        break;
      case '--ignore-local-changes':
        ignoreLocalChanges = true;
        index += 1;
        break;
      default:
        throw new Error(`Unknown argument: ${flag}`);
    }
  }

  assertSupportedAgentConfig(agentConfig);

  if (!sawExplicitMode) {
    usage();
  }
  try {
    planDoc = resolve(firstArg);
    await access(planDoc);
  } catch {
    if (topLevelMode !== 'execute') {
      throw new Error(`Plan file not found: ${firstArg}`);
    }
    planDoc = await createInlineExecutePlanDoc(process.cwd(), firstArg);
  }

  const loaded = await loadOrInitialize(planDoc, process.cwd(), agentConfig, undefined, topLevelMode, {
    ignoreLocalChanges,
  });
  assertSupportedAgentConfig(loaded.state.agentConfig);
  await executeRun(loaded.state, loaded.statePath, loaded.logger);
}

let runLogger: RunLogger | undefined;

void main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  void runLogger?.event('run.failed', {
    message,
    coderSessionHandle: error instanceof CoderRoundError ? error.sessionHandle : null,
    reviewerSessionHandle: error instanceof ReviewerRoundError ? error.sessionHandle : null,
    reviewerSubtype: error instanceof ReviewerRoundError ? error.subtype : null,
  });
  if (error instanceof Error && error.stack) {
    void runLogger?.stderr(`[fatal] ${error.stack}\n`);
  } else {
    void runLogger?.stderr(`[fatal] ${message}\n`);
  }
  if (error instanceof CoderRoundError && error.sessionHandle) {
    process.stderr.write(`[neal] ${message} (coder session: ${error.sessionHandle})\n`);
  } else if (error instanceof ReviewerRoundError && error.sessionHandle) {
    process.stderr.write(`[neal] ${message} (reviewer session: ${error.sessionHandle})\n`);
  } else {
    process.stderr.write(`[neal] ${message}\n`);
  }
  process.exit(1);
});
